### PR TITLE
fix pep8 for python3

### PR DESCRIPTION
**Pull request by Enriquelpz**

### CODE REVIEW

**Comment by cjw296** [comment]
@sastred @Enriquelpz @EnriLopezSierra - can you explain what you're trying to do here?

**Comment by sastred** [comment]
Hi @cjw296 ,

Sorry, It was a mistake and we closed the PR as soon as we realized that.

Anyway, in case you are interested, we have this fork https://github.com/APSL/fixed/ because we think this project is not maintained. The commit is just a quick fix to make the code works in Python 3.

**Comment by cjw296** [comment]
Cool :-) What's your use case going to be? There's no reason this shouldn't be a proper release-to-pypi Python package, I just never had the need. If you do, we should probably just "do it properly" :-)

**Comment by sastred** [comment]
We use `fixed` in a very old project that parses very old file formats from a couple of banks. For us it's enough to have this code in a public repo like it is now, we don't want/need to consume time packaging and releasing a proper Python package for this kind of legacy projects.

Anyway, `fixed` has been very useful, thanks for publishing it!

**Comment by cjw296** [comment]
Heh, it was for the same reason for me. I think there were some Reuters files for a previous employer, but I think I mostly used it for parsing archaic UK railways data :-)

**Pull request closed without merging**
